/*!
 * \file tlpgp1.h
 * \brief Contains the core code of tlpgp1
 * \author Alan BENIER, Martin LAGLEIZE, Nathan PRAT
 * \version 1.0
 * \date Apr 23, 2014
 */

#ifndef TLPGP1_H_
#define TLPGP1_H_

#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <unistd.h>
#include <vector>
#include <algorithm>
#include "../Data.h"
#include "problem.h"
#include "domain.h"
#include "edge.h"
#include "vertex.h"
#include "tools.h"
#include "lObjType.h"
#include "constraint.h"
#include "sat.h"
#include "graph2.h"

using namespace std;

class Tlpgp1 {
public:
	Tlpgp1();
	Tlpgp1(Domain *domain, Problem *problem);
	virtual ~Tlpgp1();

	/*!
	 * \brief tlpgp1 core function
	 */
	void constructGraph();

	/*!
	* \brief converts a graph into an vector of vector
	* (*father,vector of actions) -> (vector<vector action>)
	*/
	void vertexToActions();

private:
	/*!< pointer on the domain */
	Domain * m_domainptr;
	/*!< pointer on the problem */
	Problem * m_problemptr;
	/*!< graph generated by Graph2 */
	Vertex *m_vertex;
	/*!< graph converted by vertexToActions */
	vector<vector<DurativeAction*>> m_graph;
};

#endif /* TLPGP1_H_ */
